#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["VirtualAssistantAPI/VirtualAssistantAPI/VirtualAssistantAPI.csproj", "VirtualAssistantAPI/"]
COPY ["../VirtualAssistantBusinessLogic/VirtualAssistantBusinessLogic/VirtualAssistantBusinessLogic.csproj", "../VirtualAssistantBusinessLogic/VirtualAssistantBusinessLogic/"]
RUN dotnet restore "VirtualAssistantAPI/VirtualAssistantAPI.csproj"
COPY . .
WORKDIR "/src/VirtualAssistantAPI"

ENTRYPOINT ["tail", "-f", "/dev/null"]

#RUN dotnet build "VirtualAssistantAPI.csproj" -c Release -o /app/build


#
#FROM build AS publish
#RUN dotnet publish "VirtualAssistantAPI.csproj" -c Release -o /app/publish
#
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "VirtualAssistantAPI.dll"]
